/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fodspor;

import java.lang.instrument.Instrumentation;

public class Agent {

    public static void premain(String agentOps, Instrumentation instrumentation) {
        System.out.println("Hello from agent " + agentOps);
    }
}
